# This file was generated by GoReleaser. DO NOT EDIT.
cask "klim" do
  version "0.1.7"

  on_macos do
    on_intel do
      sha256 "1ea949182a18a710fd6a4faab28c113342a080d6830c32fa121898e861235434"
      url "https://github.com/nassiharel/klim/releases/download/v#{version}/klim_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "183916552d1ac888e98bc2d88d90236fcd4b1760d1f454a845858e7c21c03c60"
      url "https://github.com/nassiharel/klim/releases/download/v#{version}/klim_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "1bd48eb4bbe8432c5bb9fcf31aeeefd1373aa5123fbe9bb0da42edecd7e5868b"
      url "https://github.com/nassiharel/klim/releases/download/v#{version}/klim_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "bd337c8bedc5a6b3956522e31fae7df8fbe54565c19364392cb4d4c31f1df32d"
      url "https://github.com/nassiharel/klim/releases/download/v#{version}/klim_#{version}_linux_arm64.tar.gz"
    end
  end

  name "klim"
  desc "Ultimate dev tools manager"
  homepage "https://github.com/nassiharel/klim"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "klim"

  # No zap stanza required

end
