# This file was generated by GoReleaser. DO NOT EDIT.
cask "klim" do
  version "0.1.4"

  on_macos do
    on_intel do
      sha256 "13ff91fe24290c8c163800a4a47642dd95836b3507f894a4f45b9cd3d4a0801e"
      url "https://github.com/nassiharel/klim/releases/download/v#{version}/klim_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "d24faa6c95d3feb7c4e8faf76262e4c032ca53bb3e4223e30e6e3dc5905b11ca"
      url "https://github.com/nassiharel/klim/releases/download/v#{version}/klim_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "1a9629801502f6c05403135dbc513ba46495deda81c77bc05100525404a9b576"
      url "https://github.com/nassiharel/klim/releases/download/v#{version}/klim_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "993eaaae709393419a702d3744753f39b840beb8617dc91070929c74bb147c3d"
      url "https://github.com/nassiharel/klim/releases/download/v#{version}/klim_#{version}_linux_arm64.tar.gz"
    end
  end

  name "klim"
  desc "Productivity booster for dev tools — discover, standardise, automate, audit toolchains."
  homepage "https://github.com/nassiharel/klim"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "klim"

  # No zap stanza required

end
