# This file was generated by GoReleaser. DO NOT EDIT.
cask "klim" do
  version "0.1.6"

  on_macos do
    on_intel do
      sha256 "e87b5e740c5b5b8cd7babc463b04b2657e40ad579b7d67357a978df784763dfe"
      url "https://github.com/nassiharel/klim/releases/download/v#{version}/klim_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "c000cdbb8a42eb571b524a14524d1c294a8019152b3a85f080fdb039d667aa26"
      url "https://github.com/nassiharel/klim/releases/download/v#{version}/klim_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b306be88168c306c203710fb876b2964e1cde86cf19af130e50db04cb1d9848e"
      url "https://github.com/nassiharel/klim/releases/download/v#{version}/klim_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "637d71b58d3847383d5b7d1e3f0595e83c6be3093c5ef5f1bafac3a77825b0c4"
      url "https://github.com/nassiharel/klim/releases/download/v#{version}/klim_#{version}_linux_arm64.tar.gz"
    end
  end

  name "klim"
  desc "Ultimate dev tools manager"
  homepage "https://github.com/nassiharel/klim"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "klim"

  # No zap stanza required

end
