# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Klim < Formula
  desc "Deterministic developer toolchains across local machines, teams, CI, and agents."
  homepage "https://github.com/nassiharel/klim"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nassiharel/klim/releases/download/v0.1.0/klim_0.1.0_darwin_amd64.tar.gz"
      sha256 "899f5ae8497297828a2869531c66cf8dde37c9aabc160d92bbd62ae43b5dcca4"

      define_method(:install) do
        bin.install "klim"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nassiharel/klim/releases/download/v0.1.0/klim_0.1.0_darwin_arm64.tar.gz"
      sha256 "6e0698e0f86fcc41f3ae0d68944082133f04853f19ae7eb4f774d630e92f0273"

      define_method(:install) do
        bin.install "klim"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nassiharel/klim/releases/download/v0.1.0/klim_0.1.0_linux_amd64.tar.gz"
      sha256 "18f4f6c9b78384b314f305252132c1edd902c602a8298fd70a22ef0435649a7b"
      define_method(:install) do
        bin.install "klim"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nassiharel/klim/releases/download/v0.1.0/klim_0.1.0_linux_arm64.tar.gz"
      sha256 "a79292e31e149a10009a1ca531f03ab0499fa724dddd98a2469af272499098cb"
      define_method(:install) do
        bin.install "klim"
      end
    end
  end

  test do
    system bin/"klim", "version"
  end
end
