# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Klim < Formula
  desc "Productivity booster for dev tools — discover, standardise, automate, audit toolchains."
  homepage "https://github.com/nassiharel/klim"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nassiharel/klim/releases/download/v0.1.3/klim_0.1.3_darwin_amd64.tar.gz"
      sha256 "894d6f731123e0188659736f852da082f013e5fbfec6dde05b55dfeb67ad494f"

      define_method(:install) do
        bin.install "klim"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nassiharel/klim/releases/download/v0.1.3/klim_0.1.3_darwin_arm64.tar.gz"
      sha256 "1964be7317310ff9282a3c16e14858e0dfb9a59fc4dd06b42737e36411587a52"

      define_method(:install) do
        bin.install "klim"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nassiharel/klim/releases/download/v0.1.3/klim_0.1.3_linux_amd64.tar.gz"
      sha256 "bc6f483ba47b8860527bdbddff21c5b94a27428ecb81fc48ef2649c15990b5cd"
      define_method(:install) do
        bin.install "klim"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nassiharel/klim/releases/download/v0.1.3/klim_0.1.3_linux_arm64.tar.gz"
      sha256 "ca6c474070578f7d25e71354f291d73786d18fdb3d2c826177e71feacfa3a62d"
      define_method(:install) do
        bin.install "klim"
      end
    end
  end

  test do
    system bin/"klim", "version"
  end
end
