# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Klim < Formula
  desc "Productivity booster for dev tools — discover, standardise, automate, audit toolchains."
  homepage "https://github.com/nassiharel/klim"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nassiharel/klim/releases/download/v0.1.2/klim_0.1.2_darwin_amd64.tar.gz"
      sha256 "2105de65e4545c2ac94370c5b323a6ab916637ca7e9b21d6fa10903dfef305f3"

      define_method(:install) do
        bin.install "klim"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nassiharel/klim/releases/download/v0.1.2/klim_0.1.2_darwin_arm64.tar.gz"
      sha256 "2393c6d7b231e26504c55eb4f41663a809f7b3b927a8d781444344f2c5709289"

      define_method(:install) do
        bin.install "klim"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nassiharel/klim/releases/download/v0.1.2/klim_0.1.2_linux_amd64.tar.gz"
      sha256 "d82d32f1c27e0e5ef7b1d7269129b26aa911fade065ec37cb42012c0afc7f717"
      define_method(:install) do
        bin.install "klim"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nassiharel/klim/releases/download/v0.1.2/klim_0.1.2_linux_arm64.tar.gz"
      sha256 "0e712d183b4876f9cba3e50abfb7c18f44e725d34feb176704c43a3c72c43659"
      define_method(:install) do
        bin.install "klim"
      end
    end
  end

  test do
    system bin/"klim", "version"
  end
end
